# Generated by Django 2.0.4 on 2018-04-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='description',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
